export default {
    APALEO_CLIENT_ID: process.env.APALEO_CLIENT_ID,
    APALEO_CLIENT_SECRET: process.env.APALEO_CLIENT_SECRET,
    APALEO_IDENTITY_URL: process.env.APALEO_IDENTITY_URL,
    APALEO_BASE_URL: process.env.APALEO_BASE_URL,
    APALEO_PROPERTY_ID: process.env.APALEO_PROPERTY_ID,
    MAPKIT_CERT_FILE: process.env.MAPKIT_CERT_FILE,
    MAPKIT_KEY_ID: process.env.MAPKIT_KEY_ID,
    MAPKIT_TEAM_ID: process.env.MAPKIT_TEAM_ID,
    MAPKIT_ORIGIN: process.env.MAPKIT_ORIGIN,
};