export default {
    APALEO_CLIENT_ID: process.env.APALEO_CLIENT_ID,
    APALEO_CLIENT_SECRET: process.env.APALEO_CLIENT_SECRET,
    APALEO_IDENTITY_URL: process.env.APALEO_IDENTITY_URL,
    APALEO_BASE_URL: process.env.APALEO_BASE_URL,
    APALEO_PROPERTY_ID: process.env.APALEO_PROPERTY_ID,
    MAPKIT_CERT_FILE: process.env.MAPKIT_CERT_FILE,
};